name: CI

on:
  push:
    branches:
      - 'main'
  pull_request:
    branches:
      - '*'

jobs:
  Tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@fbc6f3992d24b796d5a048ff273f7fcc4a7b6c09 # v5.1.0

      # For browser tests
      - uses: browser-actions/setup-chrome@48ad923757ca74d66703209fe939badbdf80f2f4 # v2.2.0

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@0723195856401067f7a2779048b490ace7a47d7c # v5.0.2

      - name: Run checks
        run: ./gradlew check --no-daemon --stacktrace

  iOS-Tests:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@fbc6f3992d24b796d5a048ff273f7fcc4a7b6c09 # v5.1.0

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@0723195856401067f7a2779048b490ace7a47d7c # v5.0.2

      - name: Run checks and documentation
        run: ./gradlew check :kotlin-sdk:dokkaGeneratePublicationHtml --no-daemon --stacktrace
